version: "3"
services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-app
    volumes:
      - /Users/GabrieleAdmin/tunein/client:/client
  
  api-server:
    restart: unless-stopped
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - /Users/GabrieleAdmin/tunein/server:/server
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - /Users/GabrieleAdmin/tunein/mongo-data:/data/db
      - /Users/GabrieleAdmin/tunein/mongo-config:/data/configdb
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  mongo-config: {}
