# version: '3.7'
# services:
#   ui:
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#       - '5000:5000'
#     stdin_open: true
#     depends_on:
#       - api
#     networks:
#       - internal
#   api:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - '8080:8080'
#     depends_on:
#       - tunein-db
#     networks:
#       - internal
#   tunein-db:
#     container_name: mongo
#     image: mongo
#     restart: unless-stopped
#     environment:
#       MONGO_INITDB_DATABASE: tunein-app
#     ports:
#       - '27017:27017'
#     volumes:
#       - mongo_data:/data/tunein-db
#       - mongo_config:/data/configdb
#     networks:
#       - internal

# networks:
#   internal:

# volumes:
#   mongo_data: {}
#   mongo_config: {}

# version: "3"
# services:
#   react-app:
#     image: tunein-client
#     # build:
#     #   context: ./client
#     #   dockerfile: Dockerfile
#     stdin_open: true
#     ports:
#       - "3000:3000"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     networks:
#       - mern-app
#   api-server:
#     image: api-server
#     # build:
#     #   context: ./server/
#     #   dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     networks:
#       - mern-app
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo:3.6.19-xenial
#     restart: always
#     ports:
#       - "27017:27017"
#     networks:
#       - mern-app
#     volumes:
#       - mongo-data:/data/db
#       - mongo-config:/data/configdb
# networks:
#   mern-app:
#     driver: bridge
# volumes:
#   mongo-data:
#     driver: local
#   mongo-config: {}


version: "3"
services:
  react-app:
    # image: tunein-client
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mern-app
    volumes:
      - /C/Users/MEGAS/Desktop/tunein/client:/client
  
  api-server:
    restart: unless-stopped
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - /C/Users/MEGAS/Desktop/tunein/server:/server
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - /C/Users/MEGAS/Desktop/tunein/mongo-config:/data/db
      - /C/Users/MEGAS/Desktop/tunein/mongo-config:/data/configdb
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  mongo-config: {}
